<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Garp export <?php echo htmlspecialchars(ucfirst($this->name)) ?></title>
	<style>
		body { font-family: sans-serif; font-size: 12px; }
	</style>
</head>
<body>
	<h1><?php echo htmlspecialchars(ucfirst($this->name)) ?></h1>
	<table>
		<thead>
			<tr>
			<?php
				$keys = array_keys($this->data[0]);
				foreach ($keys as $key):
			?><th><?php echo htmlspecialchars($key) ?></th>
			<?php endforeach; ?></tr>
		</thead>
		<tbody>
			<?php
				foreach ($this->data as $datum):
			?><tr>
				<?php foreach ($datum as $key => $value): ?><td><?php echo htmlspecialchars($value) ?></td>
				<?php endforeach; ?></tr><?php endforeach; ?>
		</tbody>
	</table>
</body>
</html>