Ext.ns('Garp');
Garp.API = {
    "url": "<?php echo $this->baseUrl("/g/ext/api"); ?>",
    "type": "zfprovider",
	"namespace": "Garp",
    "actions": {
<?php
	$json = array();
	foreach ($this->api->actions as $action => $methods):
		$jsonClass = '"'.$action.'": [';
		$jsonMethods = array();
		foreach ($methods as $method):
			$jsonMethods[] = '{"name": "'.$method['name'].'", "len": '.$method['len'].'}';
		endforeach;
		$jsonClass .= implode(',', $jsonMethods);
		$jsonClass .= ']';
		$json[] = $jsonClass;
	endforeach;
	echo implode(',', $json);
?>
	}
};