<style>
textarea { font-family: monospace; color: lime; background: black; }
h1 { font-family: "Lucida Grande", helvetica, arial; color: #ccc; margin-bottom: 10px;}
</style>
<h1>Garp API console</h1>
<form method="post" action="<?php echo $this->baseUrl('/g/content/api') ?>" target="_response" style="float:left;margin-right:100px">
	<textarea name="request" style="width:500px;height:500px;display:block;border:1px solid #888;">{"jsonrpc": "2.0", "method": "Comment.fetch", "params": [{
  "query": {
    "User.id": "35"
  }
}], "id": "2222"}</textarea>
	<button type="submit">Submit</button>
</form>
<iframe width="500" height="500" name="_response"></iframe>