<?php if ($this->displayErrors): ?>
<h3>Exception information:</h3>
<pre><b>Message:</b> <?php echo $this->exception->getMessage() ?></pre>

<?php
	if ($this->lastQuery):
?>
<h3>Last executed query:</h3>
<pre><?php echo $this->lastQuery; ?></pre>
<?php
	endif;
?>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?></pre>

<h3>Request Parameters:</h3>
<pre><?php print_r($this->request->getParams()) ?></pre>

<?php else: ?>
	
<h1>Error 404</h1>
<p>Oeps! De opgevraagde pagina kan niet gevonden worden.</p>

<?php endif ?>
