<RoutingRules>
<?php
$templates = array();
if (!empty($this->config()->image->template)):
	$templates = $this->config()->image->template;
endif;
foreach ($templates as $tplName => $tplConfig):
	$fallback = empty($tplConfig->fallback) ? 'fallback_' . $tplName . '.jpg' : $tplConfig->fallback;
?>
    <RoutingRule>
        <Condition>
        	<KeyPrefixEquals>uploads/images/scaled/<?php echo $this->escape($tplName) ?></KeyPrefixEquals>
            <HttpErrorCodeReturnedEquals>404</HttpErrorCodeReturnedEquals>
        </Condition>
        <Redirect>
        	<ReplaceKeyWith>media/images/<?php echo $this->escape($fallback) ?></ReplaceKeyWith>
        </Redirect>
    </RoutingRule>
<?php
endforeach;
?>
</RoutingRules>
