<!doctype html>

<!--[if lte IE 7 ]><html lang="en" class="ie ie7"><![endif]--> 
<!--[if IE 8 ]><html lang="en" class="ie"><![endif]--> 
<!--[if (gt IE 8)|!(IE)]><!--> <html lang="en"><!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<meta http-equiv="cleartype" content="on">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title><?php if ($this->title): echo $this->escape($this->title).' | '; endif; ?>APP NAME</title>

		
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/base.css') ?>">
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/screen-small.css') ?>" media="only screen and (min-width: 320px)">
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/screen-medium.css') ?>" media="only screen and (min-width: 640px)">
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/screen-large.css') ?>" media="only screen and (min-width: 900px)">

		<!--[if (lt IE 9)]>
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/screen-small.css') ?>">
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/screen-medium.css') ?>">
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/screen-large.css') ?>">
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/ie-tweaks.css') ?>">
		<![endif]-->

		<script src="<?php echo $this->assetUrl('/js/libs/modernizr-2.0.6.min.js') ?>"></script>

<?php /* Uncomment when applicable:
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon.png"><!-- For iPhone 4 with high-resolution Retina display: -->
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon.png"><!-- For first-generation iPad: -->
		<link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png"><!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<link rel="shortcut icon" href="img/apple-touch-icon.png"><!-- For nokia devices: -->
*/ ?>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl('/favicon.ico') ?>">

		<?php
			if (APPLICATION_ENV !== 'production'):
				$this->script()->src('/js/libs/hashgrid.js');
		?>
		<link rel="stylesheet" href="<?php echo $this->assetUrl('/css/hashgrid.css') ?>">
		<?php
			endif;
		?>
	</head>
	<body>
		<div id="container">
			<header role="banner">

			</header>
			<div id="main" role="main">
				<?php echo $this->layout()->content ?>
			</div>
			<footer>

			</footer>
		</div>

		<!-- Grab Google CDN's jQuery. fall back to local if necessary -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
		<script>!window.jQuery && document.write(unescape('%3Cscript src="<?php echo $this->assetUrl('/js/libs/jquery-1.6.2.min.js') ?>"%3E%3C/script%3E'))</script>
		<script src="<?php echo $this->assetUrl('/js/garp/garp.front.js') ?>"></script>
		<script src="<?php echo $this->assetUrl('/js/main.js') ?>"></script>
		<?php 
			echo $this->script()->render();
			echo $this->browsebox()->config();
			echo $this->partial('partials/google-analytics.phtml', 'g', array('analyticsId' => 'UA-XXXXXXX'));
		?>

		<!-- Prompt IE 6 users to install Chrome Frame. -->
  	<!--[if lt IE 7 ]>
    	<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    	<script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  	<![endif]-->
	</body>
</html>
