<?php
header('Content-type: text/xml; charset=UTF-8');
echo '<?xml version="1.0" encoding="UTF-8" ?>'."\n";
?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<?php
if (!$this->title || !$this->description): 
	throw new Exception('<title> and <description> are required parts of the RSS specification');
	endif;
?>
	<title><?php echo $this->escape($this->title) ?></title>
	<description><?php echo nl2br($this->escape($this->description)) ?></description>
	<link><?php echo $this->fullUrl('/') ?></link>
	<atom:link href="<?php echo $this->fullUrl($this->url()) ?>" rel="self" type="application/rss+xml" />
<?php 
echo $this->layout()->content; 
?>
</channel>
</rss>
