<?php
	$ini = Zend_Registry::get('config');
	if (!$ini->google->tagmanager->id) {
		throw new Exception("Please set	google.tagmanager.id in your ini config");
	}
	
	if (APPLICATION_ENV === 'production'): ?>
	<!-- Google Tag Manager -->
	<noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $ini->google->tagmanager->id ?>" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','<?php echo $ini->google->tagmanager->id ?>');</script>
	<!-- End Google Tag Manager -->
<?php
	endif; 
