<?php
// Name
if ($this->snippet->has_name):
	$headerText  = nl2br($this->escape($this->snippet->name));
	$headerTag   = $this->headerTag ?: 'h3';
	$headerClass = $this->headerClass ?: '';

	echo '<' . $headerTag.($headerClass ? ' class="'.$headerClass.'"' : '') . '>' .
		$headerText . '</' . $headerTag . '>';
endif;

// Image
if ($this->snippet->has_image && $this->snippet->Image):
	echo '<figure>';
	// Allow scalingTemplate as well as scaling_template... to preserve backward compatibility... >.< ugh
	$scalingTpl = property_exists($this, 'scaling_template') ? $this->scaling_template : (property_exists($this, 'scalingTemplate') ? $this->scalingTemplate : null);
	echo $this->image()->render($this->snippet->Image->id, $scalingTpl);
	if (isset($this->snippet->Image->caption) && $this->snippet->Image->caption):
		echo '<figcaption>' . $this->escape($this->snippet->Image->caption) . '</figcaption>';
	endif;
	echo '</figure>';
endif;

// Text / Html
$theContent = '';
if ($this->snippet->has_text):
	$theContent = nl2br($this->escape($this->snippet->text));
	if ($this->linkify !== false):
		$theContent = $this->string()->linkify($theContent);
	endif;
	if ($this->textWrapperTag):
		$theContent = '<' . $this->textWrapperTag . '>' .
			$theContent . '</' . $this->textWrapperTag . '>';
	endif;
elseif ($this->snippet->has_html):
	$bodyClass = 'rich';
	if ($this->bodyClass):
		$bodyClass .= ' '.$this->bodyClass;
	endif;
	$theContent = '<div class="' . $bodyClass.'">' .
		$this->snippet->html . '</div>';
endif;
echo $theContent;
