<!DOCTYPE html>
<html>
	<head>
		<?php echo $this->headMeta() ?>
		<title><?php echo $this->escape($this->title) ?></title>
		<script type="text/javascript" src="<?php echo $this->baseUrl('/js/garp/ext-3.3.1/adapter/ext/ext-base-debug.js') ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('/js/garp/ext-3.3.1/ext-all-debug.js') ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('/js/garp/extux/ext.ux.zendframeworkprovider.js') ?>"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl('/g/ext/smd') ?>"></script>
		<link rel="stylesheet" href="<?php echo $this->baseUrl('/js/garp/ext-3.3.1/resources/css/ext-all.css') ?>" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl('/js/garp/ext-3.3.1/resources/css/xtheme-gray.css') ?>" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/garp/garp.css') ?>" type="text/css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/garp/garp-print.css') ?>" type="text/css" media="print">
		<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/garp/icons.css') ?>" type="text/css">
		<link id="icons" rel="stylesheet" href="<?php echo $this->baseUrl('/css/cms-icons.css') ?>" type="text/css">
		<link id="favicon" rel="icon" type="image/png" href="<?php echo $this->baseUrl('/css/garp/images/favicon.png') ?>">
	</head>
	<body>
		<?php echo $this->layout()->content ?>
	</body>
</html>