<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<?php echo $this->headMeta() ?>
		<title><?php echo $this->title ?></title>
		<link rel="icon" type="image/png" href="<?php echo $this->baseUrl('/css/garp/images/garp.png') ?>">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/garp/datamodel.css') ?>">
	</head>
	<body>
		<div id="content">
			<?php echo $this->layout()->content ?>
		</div>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js"></script>
		<script src="<?php echo $this->baseUrl('/js/garp/garp.datamodel.js') ?>"></script>
	</body>
</html>