	<?php /* _____DisplayField */ 
	if (!$this->model instanceof Garp_Spawn_Model_Abstract):
		throw new Exception('This partial requires a Garp_Spawn_Model_Base instance as $model parameter.');
	endif;
	
	$model = $this->model;
	?>
	displayFieldRenderer: function(rec){
	<?php if ($model->fields->exists('name')): ?>
		return rec.get('name') || __('New');
	<?php elseif (
		$model->fields->exists('first_name') &&
		$model->fields->exists('last_name_prefix') &&
		$model->fields->exists('last_name')
	): ?>
		return rec.get('first_name') ? (rec.get('first_name') + (rec.get('last_name_prefix') ? ' ' + rec.get('last_name_prefix') + ' ' : ' ') + (rec.get('last_name') || '')) : __('New');
	<?php else: ?>
		var out = [rec.get("<?php echo implode($model->fields->listFieldNames, '"), rec.get("') ?>")].join(" ").replace("  ", " "); 
		if (out === ' ') {
			out = __("New");
		}
		return  out;
	<?php endif; ?>
	}