<?php
	if (!$this->relation instanceof Garp_Spawn_Relation):
		throw new Exception('This partial requires a Garp_Spawn_Relation instance as $relation parameter.');
	endif;
?>
	xtype: 'inlinerelatorlabels',
	model: '<?php echo $this->relation->model ?>',
	name: '<?php echo $this->relation->model ?>_relatorlabels',
	ref: '../../../<?php echo $this->relation->model ?>_relatorlabels'
},
{
	xtype: 'inlinerelator',
	model: '<?php echo $this->relation->model ?>',
	name: '<?php echo $this->relation->model ?>_relator',
	ref: '../../../<?php echo $this->relation->model ?>_relator'	
	<?php if ($this->relation->weighable): ?>,
	weighable: true
	<?php endif;?>
