<?php 
if (!$this->relation instanceof Garp_Model_Spawn_Relation):
		throw new Exception('This partial requires a Garp_Model_Spawn_Relation instance as $relation parameter.');
	endif;
	
?>
{
	xtype: 'inlinerelatorlabels',
	model: '<?php echo $this->relation->model ?>'
},
{
	xtype: 'inlinerelator',
	model: '<?php echo $this->relation->model ?>'
	<?php if($this->relation-weighable): ?>,
	weighable: true
	<?php endif;?>
}