<?php
	if (!$this->relation instanceof Garp_Model_Spawn_Relation):
		throw new Exception('This partial requires a Garp_Model_Spawn_Relation instance as $relation parameter.');
	endif;
	if (!$this->modelSet instanceof Garp_Model_Spawn_ModelSet):
		throw new Exception('This partial requires a Garp_Model_Spawn_ModelSet instance as $modelSet parameter.');
	endif;
	if ($this->relation->model === 'Image'):
		throw new Exception('This partial is intended for related models which are not images; please use image-field.phtml for that.');
	endif;
?>
				name: '<?php echo $this->relation->column ?>',
				xtype: 'bindedfield',
				bindedField: '<?php echo $this->relation->label ?>'
			}, {
				name: '<?php echo $this->relation->label ?>',
				xtype: 'joinedrelationfield',
				bindedField: '<?php echo $this->relation->column ?>',
				fieldLabel: __('<?php echo $this->relation->label ?>'),
				allowBlank: <?php echo $this->relation->type === 'belongsTo' ? 'false' : 'true' ?>,
				<?php if (!$this->relation->editable): ?>
				disabled: true,
				<?php endif; ?>
				model: '<?php echo $this->relation->model ?>'
