<div class="listmodel">
	<h2>
		<span class="icon icon-<?php echo $this->string()->camelcasedToDashed($this->model->id) ?>"></span>
		<?php echo lcfirst ($this->model->label) ?>
	</h2>
	<ul>
		<?php
			$fields = $this->model->fields->getFields();
			foreach ($fields as $field):
				$classes = array();
				if (!$field->editable):
					$classes[] = "readonly";
				endif;
		?>
		<li class="<?php echo implode(" ", $classes) ?>"><?php echo $this->string()->underscoredToReadable($field->name, false) ?> (<?php echo $field->type ?>)</li>
		<?php endforeach; ?>
	</ul>
</div>