<article id="cookie-info">
	<h1>Informatie over Cookies op deze site</h1>
	<p>Deze site maakt gebruik van zogenaamde cookies.</p>
	<p>De volgende cookies kunt u hier mogelijk aantreffen:</p>
	<dl id="cookie-identificator" class="clearfix">
		<dt>Garp_Auth</dt>
		<dd>Wordt gebruikt voor het inlogproces. Niet voor tracking of andere doeleinden.</dd>
		<dt>Garp_Accept_Cookies</dt>
		<dd>Cookie dat aangeeft dat cookies geaccepteerd worden door de bezoeker.</dd>
		<dt>__utma</dt>
		<dt>__utmb</dt>
		<dt>__utmc</dt>
		<dt>__utmz</dt>
		<dd>Tracking cookies van Google Analytics™</dd>
		<dt>fbsr_<var>3928399283248</var></dt>
		<dd>Facebook cookie</dd>
		<dt>AWSELB</dt>
		<dd>Amazon Web Services cookie. Amazon Web Services worden gebruikt voor de hosting van bijvoorbeeld afbeeldingen.</dd>
	</dl>
	<footer>Kijk voor meer informatie over cookies op: <a href="http://nl.wikipedia.org/wiki/Cookies">Wikipedia: Cookies</a></footer>
</article>
