<style>
textarea { font-family: monospace; color: lime; background: black; }
h1 { font-family: "Lucida Grande", helvetica, arial; color: #ccc; margin-bottom: 10px;}
</style>
<h1>Garp API console</h1>
<p>
<script>
function toggleFormTarget() {
	var cbx = document.getElementById('ext-controller-cbx'),
	    form = document.getElementById('api-test-form');
	if (cbx.checked) {
		form.action = '/g/ext/api';
	} else {
		form.action = '/g/content/api';
	}
}
</script>
<input type="checkbox" id="ext-controller-cbx" onchange="toggleFormTarget()"> <label for="ext-controller-cbx">Use ExtController?</label>
</p>

<form id="api-test-form" method="post" action="<?php echo $this->baseUrl('/g/content/api') ?>" target="_response" style="float:left;margin-right:100px">
	<textarea name="request" style="width:500px;height:500px;display:block;border:1px solid #888;">{"jsonrpc": "2.0", "method": "Comment.fetch", "params": [{
  "query": {
    "User.id": "35"
  }
}], "id": "2222"}</textarea>
	<button type="submit">Submit</button>
</form>
<iframe width="500" height="500" name="_response"></iframe>
