<?php if ('1' == ini_get('display_errors')): ?>
<h3>Exception information:</h3>
<pre><b>Message:</b> <?php echo $this->exception->getMessage() ?></pre>

<?php
	if ($this->exception instanceof Zend_Db_Exception):
		$profiler = Zend_Db_Table::getDefaultAdapter()->getProfiler();
		if ($profiler):
?>
<h3>Last executed query:</h3>
<pre><?php echo $profiler->getLastQueryProfile()->getQuery(); ?></pre>
<?php
		endif;
	endif;
?>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?></pre>

<h3>Request Parameters:</h3>
<pre><?php print_r($this->request->getParams()) ?></pre>

<?php else: ?>
	
<h1>Error 404</h1>
<p>Oeps! De opgevraagde pagina kan niet gevonden worden.</p>

<?php endif ?>