<?php
/* This file was generated by Garp_Spawn_Php_Model_Base - do not edit */
class Mocks_Model_ElasticsearchBogus extends Garp_Model_Db {
	protected $_name = '_tests_elasticsearch_bogus';

	// protected $_referenceMap = array(
	// 	'Author' => array(
	// 		'refTableClass' => 'Model_User',
	// 		'columns' => 'author_id',
	// 		'refColumns' => 'id'
	// 	),
	// 	'Modifier' => array(
	// 		'refTableClass' => 'Model_User',
	// 		'columns' => 'modifier_id',
	// 		'refColumns' => 'id'
	// 	),
	// 	'Provider' => array(
	// 		'refTableClass' => 'Model_Provider',
	// 		'columns' => 'provider_id',
	// 		'refColumns' => 'id'
	// 	)
	// );


	public function init() {
		parent::init();
		$this->registerObserver(new Garp_Model_Behavior_Elasticsearchable(array('columns' => array('name', 'description', 'venue_name'))));
	}

}