<?php
/**
 * Mock models used by SluggableTest
 * These test generation of slugs in multilingual models.
 * 
 * @note: These models mimic what is generated by the spawner, just like
 * the SQL generated by the setUp method of Garp_Model_Behavior_SluggableTest.
 * If the spawner changes its output, it's a good idea to change these
 * mocks as well.
 */
class Mocks_Model_Sluggable2TestNl extends Mocks_Model_Sluggable2Test {
	protected $_name = '_sluggable_test_2_nl';
	protected $_primary = 'id';
}
