<?php if (!isset($_COOKIE['Garp_Accept_Cookies']) || 'Garp_Accept_Cookies' != $_COOKIE['Garp_Accept_Cookies']): ?>
<section id="cookie-announcement">
	<p>Deze site maakt gebruik van cookies.</p>
	<p><a href="<?php echo $this->baseUrl('/cookies/'); ?>">Meer informatie?</a></p>
	<button>Melding verbergen</button>
</section>
<?php $this->script()->block("
	$(function(){
		var elm = $('#cookie-announcement');
		elm.addClass(Garp.hasCookiesAccepted() ? 'hidden' : 'visible').find('button').click(function(){
			elm.removeClass('visible').addClass('hidden');
			Garp.acceptCookies();
		});
	});
"); ?>
<?php endif; ?>
